"""Shared mock-data loader for the MCP tools.

All tools read from ``mcp_server/data/mock_customers.json`` (generated by
``scripts/seed_mock_data.py``). This module is the single access point so the
tool modules stay thin.
"""
import json
from pathlib import Path

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "mock_customers.json"


def load_customers() -> dict:
    if not _DATA_PATH.exists():
        return {}
    return json.loads(_DATA_PATH.read_text())


def find_customer(identifier: str) -> dict | None:
    """Look a customer up by id (CUST-####) or by (case-insensitive) name."""
    if not identifier:
        return None
    customers = load_customers()
    ident = identifier.strip()
    # direct id match
    if ident in customers:
        return customers[ident]
    # case-insensitive id match
    for cid, rec in customers.items():
        if cid.lower() == ident.lower():
            return rec
    # name match (full or substring)
    low = ident.lower()
    for rec in customers.values():
        if rec.get("name", "").lower() == low or low in rec.get("name", "").lower():
            return rec
    return None


def not_found(identifier: str) -> dict:
    return {
        "found": False,
        "identifier": identifier,
        "message": f"No customer record found for '{identifier}'.",
    }
